# Generated by Django 6.0.5 on 2026-09-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_pic',
        ),
    ]
